version: '3.8'

services:
  backend:
    image: asingh2112/task-manager-backend:${TAG:-latest}
    container_name: backend
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "9090:9090"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    image: asingh2112/react-frontend:${TAG:-latest}
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=Root@123
      - MYSQL_DATABASE=taskdb
      - MYSQL_ROOT_HOST=%
      - MYSQL_DEFAULT_AUTHENTICATION_PLUGIN=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pRoot@123"]
      interval: 5s
      timeout: 10s
      retries: 30

olumes:
  mysql-data:
    driver: local

networks:
  app-network:
    driver: bridge