version: '3.8'

services:
  backend:
    image: asingh2112/task-manager-backend:latest
    container_name: backend
    restart: unless-stopped
    ports:
      - "8888:8888"
    networks:
      - app-network

  frontend:
    image: asingh2112/react-frontend:latest
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://backend:8888/api


networks:
  app-network:
    driver: bridge
