- name: Deploy Task Manager App Locally
  hosts: webserver
  become: true
  tasks:
    - name: Start MySQL container
      docker_container:
        name: mysql
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: taskdb
        state: started
        ports:
          - "3306:3306"
        restart_policy: unless-stopped

    - name: Start Backend container
      docker_container:
        name: backend
        image: asingh2112/task-manager-backend:latest
        state: started
        ports:
          - "9090:8080"
        restart_policy: unless-stopped

    - name: Start Frontend container
      docker_container:
        name: frontend
        image: asingh2112/task-manager-frontend:latest
        state: started
        ports:
          - "3000:80"
        restart_policy: unless-stopped
